// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: wrpc/e2e/testdata/echo/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *EchoRPCRequest) Reset() {
	*x = EchoRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRPCRequest) ProtoMessage() {}

func (x *EchoRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRPCRequest.ProtoReflect.Descriptor instead.
func (*EchoRPCRequest) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRPCRequest) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type EchoRPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *EchoRPCResponse) Reset() {
	*x = EchoRPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRPCResponse) ProtoMessage() {}

func (x *EchoRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRPCResponse.ProtoReflect.Descriptor instead.
func (*EchoRPCResponse) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRPCResponse) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type SleepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration uint32 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *SleepRequest) Reset() {
	*x = SleepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepRequest) ProtoMessage() {}

func (x *SleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepRequest.ProtoReflect.Descriptor instead.
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{2}
}

func (x *SleepRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SleepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SleepResponse) Reset() {
	*x = SleepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepResponse) ProtoMessage() {}

func (x *SleepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepResponse.ProtoReflect.Descriptor instead.
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{3}
}

type ProtocolErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProtocolErrorRequest) Reset() {
	*x = ProtocolErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolErrorRequest) ProtoMessage() {}

func (x *ProtocolErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolErrorRequest.ProtoReflect.Descriptor instead.
func (*ProtocolErrorRequest) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{4}
}

type ProtocolErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProtocolErrorResponse) Reset() {
	*x = ProtocolErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolErrorResponse) ProtoMessage() {}

func (x *ProtocolErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolErrorResponse.ProtoReflect.Descriptor instead.
func (*ProtocolErrorResponse) Descriptor() ([]byte, []int) {
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP(), []int{5}
}

var File_wrpc_e2e_testdata_echo_echo_proto protoreflect.FileDescriptor

var file_wrpc_e2e_testdata_echo_echo_proto_rawDesc = []byte{
	0x0a, 0x21, 0x77, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x32, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x0e, 0x45, 0x63, 0x68,
	0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x1f, 0x0a, 0x0f, 0x45, 0x63, 0x68,
	0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x2a, 0x0a, 0x0c, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb7, 0x01, 0x0a, 0x04, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x33, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x12,
	0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x6f, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x77, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x72,
	0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x65, 0x63, 0x68, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wrpc_e2e_testdata_echo_echo_proto_rawDescOnce sync.Once
	file_wrpc_e2e_testdata_echo_echo_proto_rawDescData = file_wrpc_e2e_testdata_echo_echo_proto_rawDesc
)

func file_wrpc_e2e_testdata_echo_echo_proto_rawDescGZIP() []byte {
	file_wrpc_e2e_testdata_echo_echo_proto_rawDescOnce.Do(func() {
		file_wrpc_e2e_testdata_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_wrpc_e2e_testdata_echo_echo_proto_rawDescData)
	})
	return file_wrpc_e2e_testdata_echo_echo_proto_rawDescData
}

var file_wrpc_e2e_testdata_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wrpc_e2e_testdata_echo_echo_proto_goTypes = []interface{}{
	(*EchoRPCRequest)(nil),        // 0: test.EchoRPCRequest
	(*EchoRPCResponse)(nil),       // 1: test.EchoRPCResponse
	(*SleepRequest)(nil),          // 2: test.SleepRequest
	(*SleepResponse)(nil),         // 3: test.SleepResponse
	(*ProtocolErrorRequest)(nil),  // 4: test.ProtocolErrorRequest
	(*ProtocolErrorResponse)(nil), // 5: test.ProtocolErrorResponse
}
var file_wrpc_e2e_testdata_echo_echo_proto_depIdxs = []int32{
	0, // 0: test.Echo.Echo:input_type -> test.EchoRPCRequest
	2, // 1: test.Echo.Sleep:input_type -> test.SleepRequest
	4, // 2: test.Echo.ProtocolError:input_type -> test.ProtocolErrorRequest
	1, // 3: test.Echo.Echo:output_type -> test.EchoRPCResponse
	3, // 4: test.Echo.Sleep:output_type -> test.SleepResponse
	5, // 5: test.Echo.ProtocolError:output_type -> test.ProtocolErrorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wrpc_e2e_testdata_echo_echo_proto_init() }
func file_wrpc_e2e_testdata_echo_echo_proto_init() {
	if File_wrpc_e2e_testdata_echo_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtocolErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wrpc_e2e_testdata_echo_echo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtocolErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wrpc_e2e_testdata_echo_echo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wrpc_e2e_testdata_echo_echo_proto_goTypes,
		DependencyIndexes: file_wrpc_e2e_testdata_echo_echo_proto_depIdxs,
		MessageInfos:      file_wrpc_e2e_testdata_echo_echo_proto_msgTypes,
	}.Build()
	File_wrpc_e2e_testdata_echo_echo_proto = out.File
	file_wrpc_e2e_testdata_echo_echo_proto_rawDesc = nil
	file_wrpc_e2e_testdata_echo_echo_proto_goTypes = nil
	file_wrpc_e2e_testdata_echo_echo_proto_depIdxs = nil
}
