name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Setup buf
        uses: wizhi/setup-buf@v1
        with:
          version: 1.1.0
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: install tools
        run: make install-tools
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45.0
          skip-cache: true
      - name: make test
        run: make test
      - name: Verify Codegen
        run: make verify-codegen
